import type { BuiltinCrewId, CrewId } from "../domain/xingchao/types.ts"
import type { FleetSkinManifest } from "./fleet-skin-schema.ts"

import { BUILTIN_CREW_IDS } from "../domain/xingchao/types.ts"
import { validateFleetSkinManifest } from "./fleet-skin-schema.ts"

const builtinFleetSkinEntries = {
  watchtide: validateFleetSkinManifest({
    schemaVersion: "1.0.0",
    identity: {
      crewId: "watchtide",
      name: "望潮团",
      version: "1.0.0",
      description: "深海舰桥、星图与黄铜航仪构成的指挥皮肤。",
      crest: "watchtide.crest",
    },
    palette: {
      canvas: "#07111F",
      panel: "#0D1C2D",
      elevated: "#152A3D",
      primary: "#2B6F9F",
      secondary: "#486A82",
      accent: "#D3A74F",
      text: "#F4F0E6",
      mutedText: "#AFC1CF",
      success: "#55B88A",
      warning: "#D9A441",
      danger: "#DC6B68",
      focus: "#7DD3FC",
    },
    surfaces: {
      sidebar: { material: "glass", opacity: 0.9, border: "#8B6A38", shadow: "strong", radius: 14 },
      titlebar: { material: "metal", opacity: 0.96, border: "#6D5632", shadow: "medium", radius: 0 },
      content: { material: "glass", opacity: 0.84, border: "#31566F", shadow: "soft", radius: 18 },
      card: { material: "glass", opacity: 0.88, border: "#80653C", shadow: "medium", radius: 14 },
      dialog: { material: "metal", opacity: 0.98, border: "#B38B45", shadow: "strong", radius: 12 },
      input: { material: "glass", opacity: 0.92, border: "#4C7188", shadow: "inset", radius: 12 },
      overlay: { material: "mist", opacity: 0.78, border: "#2F5269", shadow: "soft", radius: 20 },
    },
    typography: {
      heading: { family: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif', weight: 700, tracking: 0.2 },
      body: {
        family: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        weight: 400,
        tracking: 0,
      },
      numeric: {
        family: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        weight: 600,
        tracking: 0.3,
      },
      label: { family: "ui-sans-serif, system-ui, sans-serif", weight: 600, tracking: 1.1 },
    },
    scene: {
      backdrop: "watchtide.scene.backdrop",
      foreground: "watchtide.scene.foreground",
      scrim: "color-mix(in oklab, #07111F 72%, #000000 28%)",
      focalPoint: "62% 46%",
    },
    navigation: { selectedShape: "frame", divider: "notch" },
    captain: {
      layers: ["watchtide.captain.base", "watchtide.captain.uniform"],
      stage: {
        stageWidthPercent: 36,
        focalPosition: "58% 42%",
        alignment: "right",
        safeCaptionPosition: "bottom-left",
      },
      companion: {
        companionWidthPx: 280,
        focalPosition: "52% 40%",
        alignment: "right",
        safeCaptionPosition: "left",
      },
      compact: {
        compactSizePx: 56,
        focalPosition: "50% 38%",
        alignment: "center",
        safeCaptionPosition: "outside",
      },
      staticFallback: "watchtide.captain.static",
      motionStyle: "command",
    },
    motion: { switchMs: 360, parallaxPx: 18, particleDensity: 30, feedbackMs: 150 },
    audio: { cue: "bell", ambient: "none" },
    accessibility: {
      highContrast: {
        canvas: "#000000",
        panel: "#0A0A0A",
        elevated: "#161616",
        primary: "#FFFFFF",
        secondary: "#D8D8D8",
        accent: "#FFFF00",
        text: "#FFFFFF",
        mutedText: "#D8D8D8",
        success: "#00FF88",
        warning: "#FFFF00",
        danger: "#FF6B6B",
        focus: "#00FFFF",
      },
      reducedMotion: { switchMs: 0, parallaxPx: 0, particleDensity: 0 },
    },
  }),
  "ink-sail": validateFleetSkinManifest({
    schemaVersion: "1.0.0",
    identity: {
      crewId: "ink-sail",
      name: "墨帆团",
      version: "1.0.0",
      description: "暗红书斋、宣纸纹理与手稿分隔构成的编辑皮肤。",
      crest: "ink-sail.crest",
    },
    palette: {
      canvas: "#1A1012",
      panel: "#261719",
      elevated: "#332023",
      primary: "#8B3444",
      secondary: "#705052",
      accent: "#D0AA78",
      text: "#F5EADB",
      mutedText: "#C5ADA0",
      success: "#689B72",
      warning: "#D39B55",
      danger: "#C85158",
      focus: "#F3C98B",
    },
    surfaces: {
      sidebar: { material: "paper", opacity: 1, border: "#5D3437", shadow: "none", radius: 4 },
      titlebar: { material: "wood", opacity: 1, border: "#4B292C", shadow: "inset", radius: 0 },
      content: { material: "paper", opacity: 0.98, border: "#604043", shadow: "soft", radius: 6 },
      card: { material: "paper", opacity: 1, border: "#765053", shadow: "soft", radius: 3 },
      dialog: { material: "paper", opacity: 1, border: "#A06B67", shadow: "strong", radius: 4 },
      input: { material: "ink", opacity: 0.96, border: "#835B58", shadow: "inset", radius: 2 },
      overlay: { material: "ink", opacity: 0.9, border: "#6C4448", shadow: "medium", radius: 4 },
    },
    typography: {
      heading: { family: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif', weight: 800, tracking: 0.1 },
      body: { family: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif', weight: 400, tracking: 0.15 },
      numeric: {
        family: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        weight: 500,
        tracking: 0.2,
      },
      label: { family: "ui-sans-serif, system-ui, sans-serif", weight: 600, tracking: 0.8 },
    },
    scene: {
      backdrop: "ink-sail.scene.backdrop",
      foreground: "ink-sail.scene.foreground",
      scrim: "color-mix(in oklab, #1A1012 78%, #000000 22%)",
      focalPoint: "38% 44%",
    },
    navigation: { selectedShape: "ticket", divider: "line" },
    captain: {
      layers: ["ink-sail.captain.base", "ink-sail.captain.uniform"],
      stage: {
        stageWidthPercent: 34,
        focalPosition: "48% 40%",
        alignment: "right",
        safeCaptionPosition: "bottom-left",
      },
      companion: {
        companionWidthPx: 264,
        focalPosition: "50% 39%",
        alignment: "right",
        safeCaptionPosition: "left",
      },
      compact: {
        compactSizePx: 52,
        focalPosition: "50% 37%",
        alignment: "center",
        safeCaptionPosition: "outside",
      },
      staticFallback: "ink-sail.captain.static",
      motionStyle: "editorial",
    },
    motion: { switchMs: 410, parallaxPx: 8, particleDensity: 16, feedbackMs: 220 },
    audio: { cue: "paper", ambient: "none" },
    accessibility: {
      highContrast: {
        canvas: "#000000",
        panel: "#0A0A0A",
        elevated: "#161616",
        primary: "#FFFFFF",
        secondary: "#D8D8D8",
        accent: "#FFFF00",
        text: "#FFFFFF",
        mutedText: "#D8D8D8",
        success: "#00FF88",
        warning: "#FFFF00",
        danger: "#FF6B6B",
        focus: "#00FFFF",
      },
      reducedMotion: { switchMs: 0, parallaxPx: 0, particleDensity: 0 },
    },
  }),
  "brocade-harbor": validateFleetSkinManifest({
    schemaVersion: "1.0.0",
    identity: {
      crewId: "brocade-harbor",
      name: "绮港团",
      version: "1.0.0",
      description: "玉色玻璃、虹彩设计舱与珊瑚光构成的创意皮肤。",
      crest: "brocade-harbor.crest",
    },
    palette: {
      canvas: "#081A1C",
      panel: "#10272A",
      elevated: "#19363A",
      primary: "#4FA6A0",
      secondary: "#6D8E91",
      accent: "#FF8F8B",
      text: "#F2FAF8",
      mutedText: "#AFCCCA",
      success: "#64C99A",
      warning: "#F2B86B",
      danger: "#F07580",
      focus: "#8EF2E7",
    },
    surfaces: {
      sidebar: { material: "glass", opacity: 0.82, border: "#3B8581", shadow: "soft", radius: 24 },
      titlebar: { material: "glass", opacity: 0.76, border: "#4A8D8A", shadow: "none", radius: 16 },
      content: { material: "glass", opacity: 0.72, border: "#4E8E8B", shadow: "soft", radius: 28 },
      card: { material: "ceramic", opacity: 0.88, border: "#5CA19D", shadow: "medium", radius: 24 },
      dialog: { material: "glass", opacity: 0.94, border: "#79C3BD", shadow: "strong", radius: 26 },
      input: { material: "glass", opacity: 0.86, border: "#6FB8B1", shadow: "inset", radius: 22 },
      overlay: { material: "mist", opacity: 0.66, border: "#4D8D93", shadow: "soft", radius: 32 },
    },
    typography: {
      heading: { family: "ui-sans-serif, system-ui, sans-serif", weight: 700, tracking: -0.2 },
      body: { family: "ui-sans-serif, system-ui, sans-serif", weight: 400, tracking: 0 },
      numeric: { family: "Arial, Helvetica, sans-serif", weight: 600, tracking: 0.1 },
      label: { family: "ui-sans-serif, system-ui, sans-serif", weight: 600, tracking: 0.7 },
    },
    scene: {
      backdrop: "brocade-harbor.scene.backdrop",
      foreground: "brocade-harbor.scene.foreground",
      scrim: "color-mix(in oklab, #081A1C 65%, #000000 35%)",
      focalPoint: "54% 48%",
    },
    navigation: { selectedShape: "pill", divider: "none" },
    captain: {
      layers: ["brocade-harbor.captain.base", "brocade-harbor.captain.uniform"],
      stage: {
        stageWidthPercent: 38,
        focalPosition: "55% 43%",
        alignment: "right",
        safeCaptionPosition: "bottom-left",
      },
      companion: {
        companionWidthPx: 300,
        focalPosition: "54% 41%",
        alignment: "right",
        safeCaptionPosition: "left",
      },
      compact: {
        compactSizePx: 60,
        focalPosition: "52% 38%",
        alignment: "center",
        safeCaptionPosition: "outside",
      },
      staticFallback: "brocade-harbor.captain.static",
      motionStyle: "studio",
    },
    motion: { switchMs: 440, parallaxPx: 26, particleDensity: 55, feedbackMs: 190 },
    audio: { cue: "glass", ambient: "none" },
    accessibility: {
      highContrast: {
        canvas: "#000000",
        panel: "#0A0A0A",
        elevated: "#161616",
        primary: "#FFFFFF",
        secondary: "#D8D8D8",
        accent: "#FFFF00",
        text: "#FFFFFF",
        mutedText: "#D8D8D8",
        success: "#00FF88",
        warning: "#FFFF00",
        danger: "#FF6B6B",
        focus: "#00FFFF",
      },
      reducedMotion: { switchMs: 0, parallaxPx: 0, particleDensity: 0 },
    },
  }),
  "forge-vessel": validateFleetSkinManifest({
    schemaVersion: "1.0.0",
    identity: {
      crewId: "forge-vessel",
      name: "铸舟团",
      version: "1.0.0",
      description: "枪灰工程机库、刚性网格与电蓝终端构成的研发皮肤。",
      crest: "forge-vessel.crest",
    },
    palette: {
      canvas: "#0B1016",
      panel: "#141B23",
      elevated: "#1D2833",
      primary: "#277AB8",
      secondary: "#526D80",
      accent: "#38BDF8",
      text: "#E9F2F8",
      mutedText: "#A9BAC7",
      success: "#45C489",
      warning: "#E1A84E",
      danger: "#E05D62",
      focus: "#62D1FF",
    },
    surfaces: {
      sidebar: { material: "metal", opacity: 0.98, border: "#354A5B", shadow: "inset", radius: 2 },
      titlebar: { material: "metal", opacity: 1, border: "#2F4353", shadow: "none", radius: 0 },
      content: { material: "grid", opacity: 0.96, border: "#345B72", shadow: "inset", radius: 4 },
      card: { material: "metal", opacity: 0.98, border: "#3E6379", shadow: "medium", radius: 3 },
      dialog: { material: "metal", opacity: 1, border: "#4B8CAF", shadow: "strong", radius: 2 },
      input: { material: "grid", opacity: 0.96, border: "#397697", shadow: "inset", radius: 2 },
      overlay: { material: "grid", opacity: 0.88, border: "#315D74", shadow: "medium", radius: 4 },
    },
    typography: {
      heading: {
        family: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        weight: 700,
        tracking: 0.5,
      },
      body: {
        family: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        weight: 400,
        tracking: 0,
      },
      numeric: {
        family: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        weight: 600,
        tracking: 0.4,
      },
      label: {
        family: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        weight: 600,
        tracking: 1.2,
      },
    },
    scene: {
      backdrop: "forge-vessel.scene.backdrop",
      foreground: "forge-vessel.scene.foreground",
      scrim: "color-mix(in srgb, #0B1016 76%, #000000 24%)",
      focalPoint: "68% 52%",
    },
    navigation: { selectedShape: "frame", divider: "line" },
    captain: {
      layers: ["forge-vessel.captain.base", "forge-vessel.captain.uniform"],
      stage: {
        stageWidthPercent: 35,
        focalPosition: "60% 42%",
        alignment: "right",
        safeCaptionPosition: "bottom-left",
      },
      companion: {
        companionWidthPx: 276,
        focalPosition: "56% 40%",
        alignment: "right",
        safeCaptionPosition: "left",
      },
      compact: {
        compactSizePx: 54,
        focalPosition: "52% 38%",
        alignment: "center",
        safeCaptionPosition: "outside",
      },
      staticFallback: "forge-vessel.captain.static",
      motionStyle: "engineering",
    },
    motion: { switchMs: 280, parallaxPx: 12, particleDensity: 24, feedbackMs: 90 },
    audio: { cue: "relay", ambient: "none" },
    accessibility: {
      highContrast: {
        canvas: "#000000",
        panel: "#0A0A0A",
        elevated: "#161616",
        primary: "#FFFFFF",
        secondary: "#D8D8D8",
        accent: "#FFFF00",
        text: "#FFFFFF",
        mutedText: "#D8D8D8",
        success: "#00FF88",
        warning: "#FFFF00",
        danger: "#FF6B6B",
        focus: "#00FFFF",
      },
      reducedMotion: { switchMs: 0, parallaxPx: 0, particleDensity: 0 },
    },
  }),
  "golden-scale": validateFleetSkinManifest({
    schemaVersion: "1.0.0",
    identity: {
      crewId: "golden-scale",
      name: "金秤团",
      version: "1.0.0",
      description: "黑曜石交易舱、金色刻度与翠绿数据构成的量化皮肤。",
      crest: "golden-scale.crest",
    },
    palette: {
      canvas: "#0C110E",
      panel: "#141C17",
      elevated: "#1D2921",
      primary: "#267255",
      secondary: "#526D5C",
      accent: "#D6B35D",
      text: "#F4F2E8",
      mutedText: "#B7C2B9",
      success: "#40B97A",
      warning: "#D9AA47",
      danger: "#D45F61",
      focus: "#F8D879",
    },
    surfaces: {
      sidebar: { material: "metal", opacity: 0.98, border: "#76633B", shadow: "inset", radius: 6 },
      titlebar: { material: "solid", opacity: 1, border: "#5F5033", shadow: "none", radius: 0 },
      content: { material: "solid", opacity: 0.97, border: "#3E5D49", shadow: "soft", radius: 8 },
      card: { material: "metal", opacity: 0.99, border: "#8A7240", shadow: "medium", radius: 6 },
      dialog: { material: "metal", opacity: 1, border: "#B09149", shadow: "strong", radius: 4 },
      input: { material: "solid", opacity: 1, border: "#64745E", shadow: "inset", radius: 4 },
      overlay: { material: "glass", opacity: 0.9, border: "#6F613C", shadow: "medium", radius: 8 },
    },
    typography: {
      heading: { family: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif', weight: 700, tracking: 0.15 },
      body: {
        family: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        weight: 400,
        tracking: 0,
      },
      numeric: {
        family: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        weight: 700,
        tracking: 0.35,
      },
      label: { family: "ui-sans-serif, system-ui, sans-serif", weight: 700, tracking: 0.9 },
    },
    scene: {
      backdrop: "golden-scale.scene.backdrop",
      foreground: "golden-scale.scene.foreground",
      scrim: "color-mix(in oklab, #0C110E 74%, #000000 26%)",
      focalPoint: "64% 48%",
    },
    navigation: { selectedShape: "underline", divider: "line" },
    captain: {
      layers: ["golden-scale.captain.base", "golden-scale.captain.uniform"],
      stage: {
        stageWidthPercent: 34,
        focalPosition: "57% 41%",
        alignment: "right",
        safeCaptionPosition: "bottom-left",
      },
      companion: {
        companionWidthPx: 270,
        focalPosition: "53% 40%",
        alignment: "right",
        safeCaptionPosition: "left",
      },
      compact: {
        compactSizePx: 52,
        focalPosition: "50% 38%",
        alignment: "center",
        safeCaptionPosition: "outside",
      },
      staticFallback: "golden-scale.captain.static",
      motionStyle: "precision",
    },
    motion: { switchMs: 300, parallaxPx: 10, particleDensity: 12, feedbackMs: 80 },
    audio: { cue: "scale", ambient: "none" },
    accessibility: {
      highContrast: {
        canvas: "#000000",
        panel: "#0A0A0A",
        elevated: "#161616",
        primary: "#FFFFFF",
        secondary: "#D8D8D8",
        accent: "#FFFF00",
        text: "#FFFFFF",
        mutedText: "#D8D8D8",
        success: "#00FF88",
        warning: "#FFFF00",
        danger: "#FF6B6B",
        focus: "#00FFFF",
      },
      reducedMotion: { switchMs: 0, parallaxPx: 0, particleDensity: 0 },
    },
  }),
  "helm-order": validateFleetSkinManifest({
    schemaVersion: "1.0.0",
    identity: {
      crewId: "helm-order",
      name: "舵序团",
      version: "1.0.0",
      description: "暖白调度室、档案卡纸与流程节点构成的运营皮肤。",
      crest: "helm-order.crest",
    },
    palette: {
      canvas: "#F1EEE7",
      panel: "#E6E0D5",
      elevated: "#FCFAF5",
      primary: "#385D7A",
      secondary: "#6A7680",
      accent: "#B8873B",
      text: "#1B252D",
      mutedText: "#5F6A72",
      success: "#39785A",
      warning: "#9E6D21",
      danger: "#A74343",
      focus: "#155C91",
    },
    surfaces: {
      sidebar: { material: "paper", opacity: 1, border: "#C3B8A6", shadow: "none", radius: 8 },
      titlebar: { material: "paper", opacity: 1, border: "#CEC4B3", shadow: "none", radius: 0 },
      content: { material: "paper", opacity: 1, border: "#D1C7B7", shadow: "soft", radius: 10 },
      card: { material: "paper", opacity: 1, border: "#BFB3A0", shadow: "soft", radius: 8 },
      dialog: { material: "paper", opacity: 1, border: "#9F907B", shadow: "strong", radius: 8 },
      input: { material: "paper", opacity: 1, border: "#AFA38F", shadow: "inset", radius: 6 },
      overlay: { material: "paper", opacity: 0.96, border: "#B9AD99", shadow: "medium", radius: 10 },
    },
    typography: {
      heading: {
        family: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        weight: 700,
        tracking: 0,
      },
      body: {
        family: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        weight: 400,
        tracking: 0,
      },
      numeric: {
        family: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        weight: 600,
        tracking: 0.2,
      },
      label: { family: "ui-sans-serif, system-ui, sans-serif", weight: 600, tracking: 0.8 },
    },
    scene: {
      backdrop: "helm-order.scene.backdrop",
      foreground: "helm-order.scene.foreground",
      scrim: "color-mix(in srgb, #F1EEE7 84%, #FFFFFF 16%)",
      focalPoint: "46% 48%",
    },
    navigation: { selectedShape: "ticket", divider: "nodes" },
    captain: {
      layers: ["helm-order.captain.base", "helm-order.captain.uniform"],
      stage: {
        stageWidthPercent: 33,
        focalPosition: "50% 42%",
        alignment: "right",
        safeCaptionPosition: "bottom-left",
      },
      companion: {
        companionWidthPx: 252,
        focalPosition: "50% 40%",
        alignment: "right",
        safeCaptionPosition: "left",
      },
      compact: {
        compactSizePx: 48,
        focalPosition: "50% 38%",
        alignment: "center",
        safeCaptionPosition: "outside",
      },
      staticFallback: "helm-order.captain.static",
      motionStyle: "operations",
    },
    motion: { switchMs: 330, parallaxPx: 6, particleDensity: 8, feedbackMs: 140 },
    audio: { cue: "stamp", ambient: "none" },
    accessibility: {
      highContrast: {
        canvas: "#FFFFFF",
        panel: "#F7F7F7",
        elevated: "#EEEEEE",
        primary: "#000000",
        secondary: "#333333",
        accent: "#7A4300",
        text: "#000000",
        mutedText: "#333333",
        success: "#006B3C",
        warning: "#704A00",
        danger: "#9A0000",
        focus: "#005FCC",
      },
      reducedMotion: { switchMs: 0, parallaxPx: 0, particleDensity: 0 },
    },
  }),
  "iron-code": validateFleetSkinManifest({
    schemaVersion: "1.0.0",
    identity: {
      crewId: "iron-code",
      name: "铁律团",
      version: "1.0.0",
      description: "酒红审议厅、象牙卷宗与刚性边界构成的法务皮肤。",
      crest: "iron-code.crest",
    },
    palette: {
      canvas: "#160D10",
      panel: "#241317",
      elevated: "#321C21",
      primary: "#7F2938",
      secondary: "#73565B",
      accent: "#E1D1AE",
      text: "#F6EEE0",
      mutedText: "#C8B5AA",
      success: "#609568",
      warning: "#C58A3B",
      danger: "#CE4D56",
      focus: "#FFE0A3",
    },
    surfaces: {
      sidebar: { material: "paper", opacity: 0.99, border: "#6F343D", shadow: "inset", radius: 0 },
      titlebar: { material: "solid", opacity: 1, border: "#5C2932", shadow: "none", radius: 0 },
      content: { material: "solid", opacity: 0.99, border: "#6B3A43", shadow: "none", radius: 0 },
      card: { material: "paper", opacity: 1, border: "#8A5660", shadow: "medium", radius: 0 },
      dialog: { material: "paper", opacity: 1, border: "#C2A681", shadow: "strong", radius: 0 },
      input: { material: "solid", opacity: 1, border: "#98747A", shadow: "inset", radius: 0 },
      overlay: { material: "ink", opacity: 0.94, border: "#7A454D", shadow: "strong", radius: 0 },
    },
    typography: {
      heading: { family: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif', weight: 900, tracking: 0.35 },
      body: { family: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif', weight: 500, tracking: 0.05 },
      numeric: {
        family: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        weight: 700,
        tracking: 0.3,
      },
      label: { family: "Arial, Helvetica, sans-serif", weight: 700, tracking: 1.3 },
    },
    scene: {
      backdrop: "iron-code.scene.backdrop",
      foreground: "iron-code.scene.foreground",
      scrim: "color-mix(in oklab, #160D10 82%, #000000 18%)",
      focalPoint: "51% 43%",
    },
    navigation: { selectedShape: "frame", divider: "line" },
    captain: {
      layers: ["iron-code.captain.base", "iron-code.captain.uniform"],
      stage: {
        stageWidthPercent: 35,
        focalPosition: "53% 40%",
        alignment: "right",
        safeCaptionPosition: "bottom-left",
      },
      companion: {
        companionWidthPx: 268,
        focalPosition: "51% 39%",
        alignment: "right",
        safeCaptionPosition: "left",
      },
      compact: {
        compactSizePx: 50,
        focalPosition: "50% 37%",
        alignment: "center",
        safeCaptionPosition: "outside",
      },
      staticFallback: "iron-code.captain.static",
      motionStyle: "tribunal",
    },
    motion: { switchMs: 260, parallaxPx: 4, particleDensity: 6, feedbackMs: 110 },
    audio: { cue: "gavel", ambient: "none" },
    accessibility: {
      highContrast: {
        canvas: "#000000",
        panel: "#0A0A0A",
        elevated: "#161616",
        primary: "#FFFFFF",
        secondary: "#D8D8D8",
        accent: "#FFFF00",
        text: "#FFFFFF",
        mutedText: "#D8D8D8",
        success: "#00FF88",
        warning: "#FFFF00",
        danger: "#FF6B6B",
        focus: "#00FFFF",
      },
      reducedMotion: { switchMs: 0, parallaxPx: 0, particleDensity: 0 },
    },
  }),
  lighthouse: validateFleetSkinManifest({
    schemaVersion: "1.0.0",
    identity: {
      crewId: "lighthouse",
      name: "灯塔团",
      version: "1.0.0",
      description: "靛蓝知识塔、暖光书库与索引星标构成的学习皮肤。",
      crest: "lighthouse.crest",
    },
    palette: {
      canvas: "#10152A",
      panel: "#191F39",
      elevated: "#242B49",
      primary: "#4A5FA5",
      secondary: "#69759E",
      accent: "#F1C36D",
      text: "#F7F2E6",
      mutedText: "#BFC4D8",
      success: "#59A87A",
      warning: "#DDA94C",
      danger: "#D86770",
      focus: "#FFD985",
    },
    surfaces: {
      sidebar: { material: "fabric", opacity: 0.98, border: "#39446D", shadow: "inset", radius: 10 },
      titlebar: { material: "wood", opacity: 0.96, border: "#504970", shadow: "soft", radius: 0 },
      content: { material: "paper", opacity: 0.92, border: "#4D567B", shadow: "soft", radius: 14 },
      card: { material: "paper", opacity: 0.96, border: "#59658E", shadow: "medium", radius: 12 },
      dialog: { material: "wood", opacity: 0.98, border: "#88734B", shadow: "strong", radius: 10 },
      input: { material: "paper", opacity: 0.96, border: "#65709A", shadow: "inset", radius: 8 },
      overlay: { material: "mist", opacity: 0.82, border: "#485276", shadow: "soft", radius: 16 },
    },
    typography: {
      heading: { family: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif', weight: 700, tracking: 0.1 },
      body: { family: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif', weight: 400, tracking: 0.05 },
      numeric: {
        family: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        weight: 500,
        tracking: 0.2,
      },
      label: { family: "ui-sans-serif, system-ui, sans-serif", weight: 600, tracking: 0.9 },
    },
    scene: {
      backdrop: "lighthouse.scene.backdrop",
      foreground: "lighthouse.scene.foreground",
      scrim: "color-mix(in oklab, #10152A 70%, #000000 30%)",
      focalPoint: "43% 40%",
    },
    navigation: { selectedShape: "underline", divider: "notch" },
    captain: {
      layers: ["lighthouse.captain.base", "lighthouse.captain.uniform"],
      stage: {
        stageWidthPercent: 37,
        focalPosition: "56% 41%",
        alignment: "right",
        safeCaptionPosition: "bottom-left",
      },
      companion: {
        companionWidthPx: 288,
        focalPosition: "53% 40%",
        alignment: "right",
        safeCaptionPosition: "left",
      },
      compact: {
        compactSizePx: 58,
        focalPosition: "50% 38%",
        alignment: "center",
        safeCaptionPosition: "outside",
      },
      staticFallback: "lighthouse.captain.static",
      motionStyle: "mentor",
    },
    motion: { switchMs: 400, parallaxPx: 14, particleDensity: 20, feedbackMs: 210 },
    audio: { cue: "beacon", ambient: "none" },
    accessibility: {
      highContrast: {
        canvas: "#000000",
        panel: "#0A0A0A",
        elevated: "#161616",
        primary: "#FFFFFF",
        secondary: "#D8D8D8",
        accent: "#FFFF00",
        text: "#FFFFFF",
        mutedText: "#D8D8D8",
        success: "#00FF88",
        warning: "#FFFF00",
        danger: "#FF6B6B",
        focus: "#00FFFF",
      },
      reducedMotion: { switchMs: 0, parallaxPx: 0, particleDensity: 0 },
    },
  }),
  "phantom-wave": validateFleetSkinManifest({
    schemaVersion: "1.0.0",
    identity: {
      crewId: "phantom-wave",
      name: "幻浪团",
      version: "1.0.0",
      description: "霓虹声画舱、频谱线与流光轨道构成的媒体皮肤。",
      crest: "phantom-wave.crest",
    },
    palette: {
      canvas: "#090A18",
      panel: "#12142A",
      elevated: "#1B1E3A",
      primary: "#7257D8",
      secondary: "#3B8796",
      accent: "#E65DD8",
      text: "#F4F1FF",
      mutedText: "#B7B5D4",
      success: "#43C5A6",
      warning: "#E7AA4D",
      danger: "#F05D85",
      focus: "#7AE7FF",
    },
    surfaces: {
      sidebar: { material: "glass", opacity: 0.78, border: "#3E3677", shadow: "strong", radius: 22 },
      titlebar: { material: "glass", opacity: 0.7, border: "#37316A", shadow: "none", radius: 18 },
      content: { material: "glass", opacity: 0.68, border: "#315E77", shadow: "soft", radius: 26 },
      card: { material: "glass", opacity: 0.76, border: "#6848A3", shadow: "medium", radius: 20 },
      dialog: { material: "glass", opacity: 0.92, border: "#8B65CB", shadow: "strong", radius: 24 },
      input: { material: "glass", opacity: 0.82, border: "#447E99", shadow: "inset", radius: 24 },
      overlay: { material: "mist", opacity: 0.58, border: "#4D3E86", shadow: "strong", radius: 36 },
    },
    typography: {
      heading: { family: "Arial, Helvetica, sans-serif", weight: 700, tracking: -0.4 },
      body: { family: "ui-sans-serif, system-ui, sans-serif", weight: 400, tracking: 0 },
      numeric: {
        family: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        weight: 600,
        tracking: 0.5,
      },
      label: { family: "Arial, Helvetica, sans-serif", weight: 700, tracking: 1.4 },
    },
    scene: {
      backdrop: "phantom-wave.scene.backdrop",
      foreground: "phantom-wave.scene.foreground",
      scrim: "color-mix(in oklab, #090A18 62%, #000000 38%)",
      focalPoint: "58% 52%",
    },
    navigation: { selectedShape: "pill", divider: "none" },
    captain: {
      layers: ["phantom-wave.captain.base", "phantom-wave.captain.uniform"],
      stage: {
        stageWidthPercent: 38,
        focalPosition: "59% 43%",
        alignment: "right",
        safeCaptionPosition: "bottom-left",
      },
      companion: {
        companionWidthPx: 296,
        focalPosition: "56% 41%",
        alignment: "right",
        safeCaptionPosition: "left",
      },
      compact: {
        compactSizePx: 62,
        focalPosition: "52% 39%",
        alignment: "center",
        safeCaptionPosition: "outside",
      },
      staticFallback: "phantom-wave.captain.static",
      motionStyle: "media",
    },
    motion: { switchMs: 450, parallaxPx: 34, particleDensity: 72, feedbackMs: 120 },
    audio: { cue: "wave", ambient: "none" },
    accessibility: {
      highContrast: {
        canvas: "#000000",
        panel: "#0A0A0A",
        elevated: "#161616",
        primary: "#FFFFFF",
        secondary: "#D8D8D8",
        accent: "#FFFF00",
        text: "#FFFFFF",
        mutedText: "#D8D8D8",
        success: "#00FF88",
        warning: "#FFFF00",
        danger: "#FF6B6B",
        focus: "#00FFFF",
      },
      reducedMotion: { switchMs: 0, parallaxPx: 0, particleDensity: 0 },
    },
  }),
  "rest-harbor": validateFleetSkinManifest({
    schemaVersion: "1.0.0",
    identity: {
      crewId: "rest-harbor",
      name: "栖湾团",
      version: "1.0.0",
      description: "日光生活湾、亚麻与手绘旅行地图构成的生活皮肤。",
      crest: "rest-harbor.crest",
    },
    palette: {
      canvas: "#F1F0E4",
      panel: "#E4E6D7",
      elevated: "#FCFBF3",
      primary: "#557A64",
      secondary: "#778477",
      accent: "#D28A5C",
      text: "#243029",
      mutedText: "#66716A",
      success: "#4E8060",
      warning: "#A66B31",
      danger: "#AD4D4B",
      focus: "#2C6F57",
    },
    surfaces: {
      sidebar: { material: "fabric", opacity: 0.98, border: "#AEB9A6", shadow: "soft", radius: 20 },
      titlebar: { material: "paper", opacity: 0.98, border: "#C5C7B4", shadow: "none", radius: 10 },
      content: { material: "paper", opacity: 0.96, border: "#B8C1AF", shadow: "soft", radius: 22 },
      card: { material: "fabric", opacity: 0.98, border: "#A7B49F", shadow: "soft", radius: 18 },
      dialog: { material: "paper", opacity: 1, border: "#8FA189", shadow: "medium", radius: 24 },
      input: { material: "paper", opacity: 1, border: "#9CAB96", shadow: "inset", radius: 20 },
      overlay: { material: "mist", opacity: 0.82, border: "#A7B69F", shadow: "soft", radius: 30 },
    },
    typography: {
      heading: { family: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif', weight: 600, tracking: 0.05 },
      body: { family: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif', weight: 400, tracking: 0.05 },
      numeric: { family: "ui-sans-serif, system-ui, sans-serif", weight: 600, tracking: 0.1 },
      label: { family: "ui-sans-serif, system-ui, sans-serif", weight: 600, tracking: 0.7 },
    },
    scene: {
      backdrop: "rest-harbor.scene.backdrop",
      foreground: "rest-harbor.scene.foreground",
      scrim: "color-mix(in srgb, #F1F0E4 82%, #FFFFFF 18%)",
      focalPoint: "40% 46%",
    },
    navigation: { selectedShape: "pill", divider: "nodes" },
    captain: {
      layers: ["rest-harbor.captain.base", "rest-harbor.captain.uniform"],
      stage: {
        stageWidthPercent: 37,
        focalPosition: "54% 42%",
        alignment: "right",
        safeCaptionPosition: "bottom-left",
      },
      companion: {
        companionWidthPx: 286,
        focalPosition: "52% 40%",
        alignment: "right",
        safeCaptionPosition: "left",
      },
      compact: {
        compactSizePx: 60,
        focalPosition: "50% 38%",
        alignment: "center",
        safeCaptionPosition: "outside",
      },
      staticFallback: "rest-harbor.captain.static",
      motionStyle: "lifestyle",
    },
    motion: { switchMs: 420, parallaxPx: 16, particleDensity: 26, feedbackMs: 240 },
    audio: { cue: "breeze", ambient: "none" },
    accessibility: {
      highContrast: {
        canvas: "#FFFFFF",
        panel: "#F7F7F7",
        elevated: "#EEEEEE",
        primary: "#000000",
        secondary: "#333333",
        accent: "#7A4300",
        text: "#000000",
        mutedText: "#333333",
        success: "#006B3C",
        warning: "#704A00",
        danger: "#9A0000",
        focus: "#005FCC",
      },
      reducedMotion: { switchMs: 0, parallaxPx: 0, particleDensity: 0 },
    },
  }),
} satisfies Record<BuiltinCrewId, FleetSkinManifest>

export const builtinFleetSkins: Readonly<Record<BuiltinCrewId, FleetSkinManifest>> =
  Object.freeze(builtinFleetSkinEntries)

const builtinFleetSkinIds = new Set<string>(BUILTIN_CREW_IDS)

export function isBuiltinFleetSkinId(crewId: CrewId): crewId is BuiltinCrewId {
  return builtinFleetSkinIds.has(crewId)
}

export function resolveFleetSkin(crewId: CrewId): FleetSkinManifest | null {
  return isBuiltinFleetSkinId(crewId) ? builtinFleetSkins[crewId] : null
}
